### ISSUE TITLE
Missing citation Foster et al. (2022)

### ISSUE THREAD

**Issue by peterjc** [grunwaldlab/OomyceteDB#13]
The "About" page, http://oomycetedb.cgrb.oregonstate.edu/about.html source https://github.com/grunwaldlab/OomyceteDB/blob/master/website/about.html says:

> # How to cite
> A manuscript for submission is currently being drafted and will be submitted in 2-4 months.

This can be updated to list the paper:

Foster *et al.* (2022) A new oomycete metabarcoding method using the rps10 gene https://doi.org/10.1094/PBIOMES-02-22-0009-R

**Comment by zachary-foster** [comment]
Thanks! It has been updated.

**Comment by peterjc** [comment]
Surely published 2022 not 2021 as written in the https://github.com/grunwaldlab/OomyceteDB/commit/3a262295163732a2aef0d05ad86695f46860b8b5 update?

The journal page says "Published Online:19 Apr 2022"

**Comment by zachary-foster** [comment]
Odd, that one I used was copied from Google Scholar. Good catch. Thanks! Should be fixed now

**Comment by peterjc** [comment]
Fixed in adcb3b928c8b227e0bc2df1d91aec603ffffe907
